### ISSUE TITLE
ColumnLayout Vaadin8

### ISSUE THREAD

**Issue by ado2000** [alump/ColumnLayout#12]
Hi,

i receive this error on the vadim 8 application screen.

Widgetset 'com.vaadin.v7.Vaadin7WidgetSet' does not contain an implementation for org.vaadin.alump.columnlayout.ColumnLayout. Check the connector's @Connect mapping, the widgetset's GWT module description file and re-compile your widgetset. In case you have downloaded a vaadin add-on package, you might want to refer to 

is this a problem of the component ?

i added the 0.3.1 version of the component.

Thanks
Giovanni

**Comment by alump** [comment]
You can not use Vaadin7WidgetSet directly, as you need to extend it with additional add-ons you are using. Create your own widgetset inheriting Vaadin7WidgetSet and add-ons you use. Then use this widgetset with your application.

This applies to all already compiled widgetset.

**Comment by ado2000** [comment]
Thanks, i'll try
