### ISSUE TITLE
Wrapping columns

### ISSUE THREAD

**Issue by yoursnowyfriendleo** [alump/ColumnLayout#7]
I am getting
LOGGER.severe("wrapping " + i + ": " + element.getAbsoluteTop() + " " + getContentElement().getAbsoluteTop());
error when updating column width. I also think this slow down rendering the colums.

Another thing, I am not able to "define" two columns unless I define

.column-panel-content {
 display: -webkit-box; //e.i. for chrome
}

in css, but in this case resizing the browser window the "second" column is hidden not moved under the "first" column. Any suggestion? Do I need to define some other styling?

I have checked Simple Example and http://app.siika.fi/ColumnLayoutDemo/#!Test for two columns but manage to get only one unless .css styling.

Cheers, Simon

**Comment by alump** [comment]
Yeah, I have left debug print with wrong severity behind. To be removed soon.

But two columns issue... can you share screenshot when how it looks when it fails to render two columns.

Also remember to define width for column layout, and it's parent. Unknown widths could be source of issues when column layout is trying to calculate the width of columns.

**Comment by yoursnowyfriendleo** [comment]
My parent VerticalLayout .details has width=600px !important; therefore column has width=300px !important.

As I am not allowed to post any screenshots to public forum (github) I am sending some screenshots + some questions on your mail.

Cheers, Simon

**Comment by LukaszByczynski** [comment]
Could you fix logging to SEVERE in next build? It's produces tons of annoying messages in console log.

**Comment by alump** [comment]
Sure, sorry didn't notice severe logging was left there. It's now removed from 0.2.1

**Comment by LukaszByczynski** [comment]
Thanks. Unfortunately, I have another SEVERE messages in console. This time from vaadin LayoutManager:

com.vaadin.client.LayoutManager
SEVERE: ColumnLayoutConnector (78) has been layouted 3 times

**Comment by alump** [comment]
Ok, I have to investigate that issue. Can you create new ticket for that as I assume fixing that might take some time.

**Comment by alump** [comment]
I couldn't find easy way to reproduce the "has been layouted" severe warning.

Also closing this ticket, as I am not sure anymore what is broken here.
