### ISSUE TITLE
placeholder and Alliging vertically first element of column

### ISSUE THREAD

**Issue by lipodido** [alump/ColumnLayout#8]
Hi,
i'm facing the same issue as showed in your  demo Issue2 , the Item: 0 0 and Item : 01 are not correctly aligned (vertically) , is it possible to remove the placeholder just for element Item 0 1 ?

regards

**Comment by lipodido** [comment]
ok i found it , i had to fixe the width of my textArea in column 0;  in the generated CSS, the column 1 was considered as "column wrap" and not as a "column" !!

**Comment by alump** [comment]
I assume this issue can be closed. Placeholders have the indexes in their classnames, so setting "display: none" style should be easy to specific placeholders.
