### ISSUE TITLE
Vaadin 7.4.6

### ISSUE THREAD

**Issue by rabinxyz** [alump/ColumnLayout#9]
Hi I have problem with widget compilation when try to use this component with Vaadin 7.4.6.

Can You check that?

Thanks

**Comment by LukaszByczynski** [comment]
Can you upload log file with error and stacktrace?

**Comment by rabinxyz** [comment]
Hi this problem only exists when I use custom ConnectorBundleLoaderFactory for app performance optimizations. I'll provide logs soon.

**Comment by alump** [comment]
No logs, closing.
